# Service & Outreach

## University Service

```{r service}
library(vitae)

library(lubridate)
vroom::vroom("data/committees-service.csv") %>%

    mutate(date = as.Date(start, "%m/%Y")) %>%
    arrange(desc(date)) %>%
    vitae::detailed_entries( # Order of entries is a little weird here, but it looks good
        where = where,
        when = glue::glue("{start} - {stop}"),
        with = with,
    )
  # vitae::brief_entries(with, when, what)#, where)
```


## Founding Member, OoLEN (Origins of Life Early Career Network)

The Origin of Life Early career Network (OoLEN) supports and accelerates research on the Origin of Life by bringing together early-career scientists from very different disciplines and backgrounds. I founded this network together with Dr Joana Xavier, Dr Martina Preiner and Silke Asche. More information can be found at [oolen.org](https://oolen.org/).

## Conference Organizer
- Interdisciplinary Origin of Life Meeting for Early Career Researchers, University of Montreal, August 2022.
- New Frontiers in the Origins of Life, Santa Fe Institute, March 2022.
- Satellite Session, Conference on Complex Systems, Arizona State University, October 2015.

## Refereeing
- Astrobiology
- Life (MDPI)
- Nature Astronomy
- Scientific Reports
- Journal of the Royal Society: Interface Focus
- PloS Computational Biology,
- Journal of Molecular Evolution,
- Journal of the Royal Society: Phil Trans A 
